output_dir: checkpoints/ace05_cts/

model:
  bert_model_name: bert-base-uncased
  adapter_bottleneck_size: 96
  num_labels: 34
  num_bert_layers: 12
  hidden_size: 768
  dropout: 0.1
  classifier_hidden_div: 1
  dann_hidden_size: 200
  dann_hidden_div: 4
  dann_layers: 2
  grl_lambda: 0.1
  spl_hidden_div: 2
  spl_layers: 2
  mwn_hidden_div: 2
  mwn_layers: 2

train:
  learning_rate: 1.0e-5
  meta_train_lr: 1.0e-4
  meta_val_lr: 1.0e-3
  weight_decay: 0.0
  batch_size: 150
  target_ratio: 0.2
  num_epochs: 200
  num_meta_train_steps: 2
  meta_test_beta: 1.0
  first_order: false
  eval_steps: 200
  save_steps: 1000
  seed: 3006
  src_pretrain_epochs: 20
  pseudo_label: true
  dann_wtype: mwn
  age_clamp: 0.5

data:
  task: ed
  train_file: data/ace2005/
  dev_file: data/ace2005/
  test_file: data/ace2005/
  source_domains:
    - bn
    - nw
  target_domain: cts
  max_seq_length: 53
